--
-- PostgreSQL database dump
--

\restrict EYPO0FHVL8Tapu7jyxczeRf5dNVsg9kLcMbD0io3PpwxzWvFlGNLi1fuNji0Xof

-- Dumped from database version 15.14
-- Dumped by pg_dump version 15.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO admin;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO admin;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO admin;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO admin;

--
-- Name: ems_category; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.ems_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.ems_category OWNER TO admin;

--
-- Name: ems_category_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.ems_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_event; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.ems_event (
    id bigint NOT NULL,
    event_id character varying(20) NOT NULL,
    name character varying(150) NOT NULL,
    project_type character varying(50) NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    description text NOT NULL,
    location character varying(255) NOT NULL,
    organizer character varying(100) NOT NULL,
    participants text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.ems_event OWNER TO admin;

--
-- Name: ems_event_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.ems_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_outcome; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.ems_outcome (
    id bigint NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    duration double precision NOT NULL,
    rappo character varying(150) NOT NULL,
    topics text NOT NULL,
    outcome_text text NOT NULL,
    recommendation text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    event_id bigint NOT NULL
);


ALTER TABLE public.ems_outcome OWNER TO admin;

--
-- Name: ems_outcome_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.ems_outcome ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_outcome_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_group (id, name) FROM stdin;
2	Site Admins
1	Study Staffs
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
1	1	32
2	1	33
3	1	34
4	1	36
5	1	25
6	1	28
7	1	29
8	1	30
9	2	13
10	2	16
11	2	17
12	2	18
13	2	19
14	2	20
15	2	21
16	2	22
17	2	23
18	2	24
19	2	25
20	2	26
21	2	27
22	2	28
23	2	29
24	2	30
25	2	31
26	2	32
27	2	33
28	2	34
29	2	35
30	2	36
31	1	26
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add category	7	add_category
26	Can change category	7	change_category
27	Can delete category	7	delete_category
28	Can view category	7	view_category
29	Can add event	8	add_event
30	Can change event	8	change_event
31	Can delete event	8	delete_event
32	Can view event	8	view_event
33	Can add outcome	9	add_outcome
34	Can change outcome	9	change_outcome
35	Can delete outcome	9	delete_outcome
36	Can view outcome	9	view_outcome
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$aekXKNPlWur8RJx7fOYkgT$As6YM+1IlRFvtUoe2TtBNPoVIgOa8UPGrrzHpgcntYo=	2026-05-11 14:32:01.450778+00	t	rowino			robindev77@gmail.com	t	t	2025-12-06 22:13:05.154885+00
3	pbkdf2_sha256$1000000$1W4K1pcXz08gtOym9tyFdH$4Jelq4ogjh6UuT+yME4/wKPBD0BCb8iretLGTOKS0jc=	2026-05-11 14:32:53.110768+00	f	kmbote	Kelvin	Mbote		f	t	2025-12-09 16:58:38+00
2	pbkdf2_sha256$1000000$WzTP75ls36O3x2zJF2x1eB$0vuJxI1ZbCCv+O/jjQbz+8z5ejwGvWHxruGjnYRdzJY=	2026-05-14 05:52:49.028042+00	f	rokello	Robin	Owino	owinorobin05@gmail.com	t	t	2025-12-08 11:48:10+00
4	pbkdf2_sha256$1000000$NJ7pkQhKc9oRlixPA1Kd8Y$9fgQdgVHq6/Stlf7VfDB0YYJ/A0DNtEzATVVr7Yz/uI=	2026-01-12 11:26:35.478027+00	f	onesw	Onesmus	Wanje		f	t	2025-12-09 17:08:56+00
5	pbkdf2_sha256$1000000$8AMKT3QWNqdvuI2Ej4qfNp$qf+qoHoDrmLho5dAbALRmh3MyYsjCbYdSKTAZHZphKI=	\N	f	misaac	Isaac	Mwaniki		f	t	2025-12-09 17:10:46+00
6	pbkdf2_sha256$1000000$Gl1SUX8fFbHkgyYaZMiyNz$6mMKhq/H1qyI3bQfkgFMN3nSJz/QxRQsu7DDj+OaGH8=	2025-12-09 17:25:31.857194+00	f	akoech	Angela			f	t	2025-12-09 17:12:23+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
2	3	1
3	4	1
4	5	1
5	6	1
6	2	1
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
1	2	32
2	2	33
3	2	34
4	2	35
5	2	36
6	2	25
7	2	26
8	2	27
9	2	28
10	2	29
11	2	30
12	2	31
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-12-08 11:44:17.799139+00	1	Study Staffs	1	[{"added": {}}]	3	1
2	2025-12-08 11:46:09.190934+00	2	Site Admins	1	[{"added": {}}]	3	1
3	2025-12-08 11:48:11.577352+00	2	rokello	1	[{"added": {}}]	4	1
4	2025-12-08 11:49:17.665391+00	2	rokello	2	[{"changed": {"fields": ["First name", "Last name", "Email address", "Staff status", "Groups"]}}]	4	1
5	2025-12-08 12:01:16.39619+00	2	rokello	2	[{"changed": {"fields": ["Staff status"]}}]	4	1
6	2025-12-09 16:58:39.139674+00	3	kmbote	1	[{"added": {}}]	4	1
7	2025-12-09 16:59:41.224379+00	3	kmbote	2	[{"changed": {"fields": ["First name", "Last name", "Groups"]}}]	4	1
8	2025-12-09 17:08:56.903664+00	4	onesw	1	[{"added": {}}]	4	1
9	2025-12-09 17:09:53.493696+00	4	onesw	2	[{"changed": {"fields": ["First name", "Last name", "Groups"]}}]	4	1
10	2025-12-09 17:10:47.087865+00	5	misaac	1	[{"added": {}}]	4	1
11	2025-12-09 17:11:09.576665+00	5	misaac	2	[{"changed": {"fields": ["First name", "Last name", "Groups"]}}]	4	1
12	2025-12-09 17:12:23.839864+00	6	akoech	1	[{"added": {}}]	4	1
13	2025-12-09 17:12:55.868117+00	6	akoech	2	[{"changed": {"fields": ["First name", "Groups"]}}]	4	1
14	2025-12-09 17:15:23.669696+00	3	kmbote	2	[{"changed": {"fields": ["password"]}}]	4	1
15	2025-12-09 17:20:49.567135+00	1	Study Staffs	2	[{"changed": {"fields": ["Permissions"]}}]	3	1
16	2026-01-26 09:56:17.620194+00	2	rokello	2	[{"changed": {"fields": ["User permissions"]}}]	4	1
17	2026-01-28 12:05:18.58942+00	2	rokello	2	[{"changed": {"fields": ["Groups"]}}]	4	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	ems	category
8	ems	event
9	ems	outcome
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-12-06 22:09:59.274323+00
2	auth	0001_initial	2025-12-06 22:09:59.352433+00
3	admin	0001_initial	2025-12-06 22:09:59.374152+00
4	admin	0002_logentry_remove_auto_add	2025-12-06 22:09:59.38113+00
5	admin	0003_logentry_add_action_flag_choices	2025-12-06 22:09:59.388361+00
6	contenttypes	0002_remove_content_type_name	2025-12-06 22:09:59.403668+00
7	auth	0002_alter_permission_name_max_length	2025-12-06 22:09:59.411095+00
8	auth	0003_alter_user_email_max_length	2025-12-06 22:09:59.418506+00
9	auth	0004_alter_user_username_opts	2025-12-06 22:09:59.424932+00
10	auth	0005_alter_user_last_login_null	2025-12-06 22:09:59.432126+00
11	auth	0006_require_contenttypes_0002	2025-12-06 22:09:59.43375+00
12	auth	0007_alter_validators_add_error_messages	2025-12-06 22:09:59.440354+00
13	auth	0008_alter_user_username_max_length	2025-12-06 22:09:59.451248+00
14	auth	0009_alter_user_last_name_max_length	2025-12-06 22:09:59.458357+00
15	auth	0010_alter_group_name_max_length	2025-12-06 22:09:59.466625+00
16	auth	0011_update_proxy_permissions	2025-12-06 22:09:59.47318+00
17	auth	0012_alter_user_first_name_max_length	2025-12-06 22:09:59.480714+00
18	ems	0001_initial	2025-12-06 22:09:59.536621+00
19	sessions	0001_initial	2025-12-06 22:09:59.551255+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
q11x1v1kyo8bya8tdkxqnge2b2kn44uu	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vTQMq:_nk2MpGLcQx5oUP1QmYYU9OtDKafmG5kCdPsL7MJLb0	2025-12-10 20:15:56.280259+00
i95wtj444rzixc9bhxcuppusw41ziyet	.eJxVjMEOwiAQBf-FsyFAgYJH7_0GsguLVA0kpT0Z_92Q9KDXNzPvzQIcewlHpy2siV3ZxC6_G0J8Uh0gPaDeG4-t7tuKfCj8pJ0vLdHrdrp_BwV6GXX2Dm2UxkaS0QujtcwZnSKUAvUsICnvdE4I0iPM2iWYlJbekiCPhn2-9Uo4Mg:1vkJdK:uKzsHQX3IO1IIiScnop5DbOFPTm__2pjEEZUkt37_gM	2026-01-26 10:30:46.261852+00
tz6jw1q108rsb3ei1ojtq35xhddbudgw	.eJxVjEsOwjAMBe-SNYrqJm4Sluw5Q2XHLi2gROpnhbg7VOoCtm9m3sv0tK1jvy0695OYswFz-t2Y8kPLDuRO5VZtrmWdJ7a7Yg-62GsVfV4O9-9gpGX81twRILQJkw8gCUCocZyTNgg5tBg9xsjOO1YN3eBzM7CQUxQK0UVv3h_DWzdz:1vToLx:jVvqZlzzRxrfxCa98p6pN_tu9_kGfSrPfYt6hGEpSFg	2025-12-11 21:52:37.071038+00
26rkfcvcd7vdywjc21epzc6d30amqmt5	.eJxVjEsOwjAMBe-SNYrqJm4Sluw5Q2XHLi2gROpnhbg7VOoCtm9m3sv0tK1jvy0695OYswFz-t2Y8kPLDuRO5VZtrmWdJ7a7Yg-62GsVfV4O9-9gpGX81twRILQJkw8gCUCocZyTNgg5tBg9xsjOO1YN3eBzM7CQUxQK0UVv3h_DWzdz:1vS101:z-VCSzI9B7ay_kk3WRWPv_ckTUqSS0mnNPIHYI41PI8	2025-12-06 22:58:33.695263+00
hz2gecx6zavnr6pejtzsnixajzmjt648	.eJxVjEsOwjAMBe-SNYrqJm4Sluw5Q2XHLi2gROpnhbg7VOoCtm9m3sv0tK1jvy0695OYswFz-t2Y8kPLDuRO5VZtrmWdJ7a7Yg-62GsVfV4O9-9gpGX81twRILQJkw8gCUCocZyTNgg5tBg9xsjOO1YN3eBzM7CQUxQK0UVv3h_DWzdz:1vS1dK:wIF2TpGdv_CGPCd74XU0Y4ls4b8mefvgXeMHh4Uc0kQ	2025-12-06 23:39:10.739811+00
rceer5oia2vo6wz9j7h2xkmkcr4eb79n	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vyBr5:ZQD40WuD_EVUjrULoQ9K3ZNgoqq97Oedmbyjx4KseBc	2026-03-05 17:18:59.495123+00
wd4kq2ychtragvxx5o0yoeqbvdu62nvf	.eJxVjEsOwjAMBe-SNYrqJm4Sluw5Q2XHLi2gROpnhbg7VOoCtm9m3sv0tK1jvy0695OYswFz-t2Y8kPLDuRO5VZtrmWdJ7a7Yg-62GsVfV4O9-9gpGX81twRILQJkw8gCUCocZyTNgg5tBg9xsjOO1YN3eBzM7CQUxQK0UVv3h_DWzdz:1vSUML:U0UAMoPcVZEoqXJllgknhh7qycy_bGGloIwitvGUQQA	2025-12-08 06:19:33.497412+00
t5w54wn63ifl949o3nrk1ef3ajow1n5s	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vVrKS:neb9B6ffVF0RLiYxxCkilKQ7SCYoh7WvB35V7WnOins	2025-12-17 13:27:32.78567+00
xqoljmx3cwtoj9ve579qlmuzflxbunz5	.eJxVjEsOwjAMBe-SNYrqJm4Sluw5Q2XHLi2gROpnhbg7VOoCtm9m3sv0tK1jvy0695OYswFz-t2Y8kPLDuRO5VZtrmWdJ7a7Yg-62GsVfV4O9-9gpGX81twRILQJkw8gCUCocZyTNgg5tBg9xsjOO1YN3eBzM7CQUxQK0UVv3h_DWzdz:1vSYjf:qf-nLPI8j11MTu0obv3_IuGcVDwwQUR_Ra8LW-xe34Y	2025-12-08 10:59:55.752325+00
6vu7tav9nl7kkwwm63d9n8ac5yx0ujd6	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vdjXr:22kTSHfxrweMXBmNeQ-Y86Xna-CdOs2mlJwdUhfp1XE	2026-01-08 06:45:55.357784+00
05b53ahng0l9e7fioqbpzdt4y88rvjsm	.eJxVjEsOwjAMBe-SNYrqJm4Sluw5Q2XHLi2gROpnhbg7VOoCtm9m3sv0tK1jvy0695OYswFz-t2Y8kPLDuRO5VZtrmWdJ7a7Yg-62GsVfV4O9-9gpGX81twRILQJkw8gCUCocZyTNgg5tBg9xsjOO1YN3eBzM7CQUxQK0UVv3h_DWzdz:1vSZLg:4I5Rz_WtL4zrKIGzONe_UwBB6R1EijbdgT_A0dip-c0	2025-12-08 11:39:12.03041+00
9rolf8ge2eltrk420nwf8p995roc560j	.eJxVjEsOwjAMBe-SNYrqJm4Sluw5Q2XHLi2gROpnhbg7VOoCtm9m3sv0tK1jvy0695OYswFz-t2Y8kPLDuRO5VZtrmWdJ7a7Yg-62GsVfV4O9-9gpGX81twRILQJkw8gCUCocZyTNgg5tBg9xsjOO1YN3eBzM7CQUxQK0UVv3h_DWzdz:1vSZbJ:AV7CTEjc99AUSOsb6PZDfz__yp_HRfiYSd-CKs8LN9k	2025-12-08 11:55:21.095538+00
zyzccgz6tw4bofv1t6zclkcu837xqmmp	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vVsHF:1u13QCTdcpS3g06EI1Wa6TjGUbuWEXJHJQcgg5uMUTk	2025-12-17 14:28:17.692279+00
rz1kibt6gi7dnma20412cahh1eyn97xu	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vT1Tk:DkyKqJ32IqUN8Wk7Aso16UelQM-UvU5jyLMLD9v7naU	2025-12-09 17:41:24.428487+00
5howpresc6ygj87l58kx07cll0q2i6e7	.eJxVjMsOwiAQRf-FtSFSXoNL935DMzCDVA0kpV0Z_92QdKHbe865bzHjvpV577zOC4mLMOL0u0VMT64D0APrvcnU6rYuUQ5FHrTLWyN-XQ_376BgL6P27PV5ohANR5ysQ002OGQFCayjYMESmEBZK3ZGZ0-gIHsXQCdwSXy-5kw3qg:1vfG4i:6qaf2n7GZpoFN8IhKLkURqU1iyhcnuz2YxQD5VhrvSQ	2026-01-12 11:42:08.622609+00
nw1bjll653xkgk6zj31fpjfnq8lyaey5	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vkht1:jOlr2QxqJLrGp4BKtbCnCCEOteQfeXMwIE7f_S2NnPc	2026-01-27 12:24:35.164026+00
0l7sbgqaoi9h8j8r53apy7ltad3xh0bn	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vhpiL:4Lda1bkuOTFzg6PWGjfsaQcs1-Z9_055bSCdIvgeozk	2026-01-19 14:09:41.752776+00
tgu062nglnz8i3dqtidv458esbv3ueil	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vWJee:lVB3GKJaJVHHZeEIN5794GpIQuWDzXDzqRKBHBUFIGI	2025-12-18 19:42:16.744512+00
srgzqmzspamakyowh3z0ebytog0zwgv8	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vT1ny:wahMM-4R82PEAfCw8m8xFFJqaBwm_iUGXMThdD2LMkQ	2025-12-09 18:02:18.336084+00
ygd6rsxn8fokf20k8iqrj7coas6o5q44	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vkidA:PsTHVOh9YG7hzCgXftbIGxXOzZTuRCRlombnK6a9sQc	2026-01-27 13:12:16.86136+00
4doo7povd9uewctmhdc3vxlwl3wff6b9	.eJxVjMEOwiAQBf-FsyFAgYJH7_0GsguLVA0kpT0Z_92Q9KDXNzPvzQIcewlHpy2siV3ZxC6_G0J8Uh0gPaDeG4-t7tuKfCj8pJ0vLdHrdrp_BwV6GXX2Dm2UxkaS0QujtcwZnSKUAvUsICnvdE4I0iPM2iWYlJbekiCPhn2-9Uo4Mg:1vT1Ny:RyX78WFitP0j_hS9kHptvVHPmVB9xBHPxw5PJV7LQNQ	2025-12-09 17:35:26.818891+00
ln1cryj577yarvk8mvgm81it3x7ld4h0	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vkiwg:wpREjtJ1vMPFz_zBN7gozN_icrHth21ZfrprS6SaaFQ	2026-01-27 13:32:26.168338+00
kesiddzot4r79drw681nj2mh860gekle	.eJxVjEsOwjAMBe-SNYrqJm4Sluw5Q2XHLi2gROpnhbg7VOoCtm9m3sv0tK1jvy0695OYswFz-t2Y8kPLDuRO5VZtrmWdJ7a7Yg-62GsVfV4O9-9gpGX81twRILQJkw8gCUCocZyTNgg5tBg9xsjOO1YN3eBzM7CQUxQK0UVv3h_DWzdz:1vkJMt:4hkdkkUnhSia7WFHgt2TkLhuZE8sisc2CzFbZWMKNnU	2026-01-26 10:13:47.238489+00
tcojizidtws68ax0mpiyra04i0p56ojj	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vX3Q4:sLPRsUyguTika32unwymT7wwhqtAyKgU1UGkH6ai960	2025-12-20 20:34:16.468482+00
yg2das24vto1gn7t8mqoyxcynzsvng2a	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vT4XE:K_9PG-qJ1llZOmdakAsMGhZp0fk13Xm8-RGvO5K53Dk	2025-12-09 20:57:12.330248+00
l6nqlwf56u35kh8bbhqwgkuuf1murn5a	.eJxVjMEOwiAQBf-FsyFAgYJH7_0GsguLVA0kpT0Z_92Q9KDXNzPvzQIcewlHpy2siV3ZxC6_G0J8Uh0gPaDeG4-t7tuKfCj8pJ0vLdHrdrp_BwV6GXX2Dm2UxkaS0QujtcwZnSKUAvUsICnvdE4I0iPM2iWYlJbekiCPhn2-9Uo4Mg:1wMRjz:gbZvNusdM34KiZLv4uUezzOCro0rUMReIrDwXQEyJgQ	2026-05-11 15:07:55.981032+00
xmcpb0aqqj9lm3x8l7pe9yydudg06l1x	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vyNP0:PsdnYL9fP9EoC0BhD-UiHiCjxt_Gblpmx1yQY0wSBDU	2026-03-06 05:38:46.327727+00
2x09t0eo1dud3vef6oc3nvxfa07t5652	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1wMUFF:TBnmsaRGfcWzIJbz-jxstvLq1lQ2XUeQxwZn4oyEEMY	2026-05-11 17:48:21.219525+00
cg2d1mxf0lbpos51v7l6yava0o7pf6ly	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1wMfYl:xwMTiuicApvQltTJ60Oa6w3D-7l7uGDGXOnm-jJN6DQ	2026-05-12 05:53:15.452833+00
4r875je7cogh4pd0aqkqxw6r13r7pj5c	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vnWrc:Cy2GB6cH_3kYqjy7GZLbhu5k2O2WmjsL4jf6-aIAfFU	2026-02-04 07:31:28.232271+00
83431bq0xy6fh6zokeqt4h1f506i8tkz	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1vkjct:dks7qu7aMuAueSPmOVHpSg1J2PpgEbxEzCK000vaYOA	2026-01-27 14:32:43.864313+00
74e436xmvuxyfnky5bdkfynl7m98enxt	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1wN42G:-x5buNoW8zi3PWcEMDAZWXfJkVdxon58--4m0wkez3A	2026-05-13 08:01:20.427434+00
da2sxrj05z7p5zmmg1kn6owmps490cwl	.eJxVjEsOwjAMBe-SNYrqJm4Sluw5Q2XHLi2gROpnhbg7VOoCtm9m3sv0tK1jvy0695OYswFz-t2Y8kPLDuRO5VZtrmWdJ7a7Yg-62GsVfV4O9-9gpGX81twRILQJkw8gCUCocZyTNgg5tBg9xsjOO1YN3eBzM7CQUxQK0UVv3h_DWzdz:1wMRgg:KYKVYN5Ql_bppqsbsdLF9of98cjPrnvnWBYTDIC9fko	2026-05-11 15:04:30.189105+00
7cekuwzedbkj7bnpeyrj0a93jh6xkcpf	.eJxVjEEOwiAQRe_C2hA6DmVw6b5nIDNApWpoUtqV8e7apAvd_vfef6nA21rC1vISpqQuCtTpdxOOj1x3kO5cb7OOc12XSfSu6IM2PcwpP6-H-3dQuJVvTaNPQkBOSDxFZEGOxiM4iNQZzBZSbx0Qgu-SARgZzdk66W00jE69P9IDNuU:1wNPyg:Fqa0Bj4zPmofBULaNTbGs5vEPHUA6ewKe3dLrmWuc4M	2026-05-14 07:27:06.363523+00
\.


--
-- Data for Name: ems_category; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.ems_category (id, name) FROM stdin;
1	ETL Development
2	CAB Meeting
3	EMR User Training
4	Technical Review Meeting
5	Development and Version Tracking
\.


--
-- Data for Name: ems_event; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.ems_event (id, event_id, name, project_type, start_date, end_date, description, location, organizer, participants, created_at, updated_at, category_id, user_id) FROM stdin;
2	EV-20251209-6C2	Data Clerk Training - Taifa Care Registration	kwp2	2025-11-13 08:00:00+00	2025-11-14 15:00:00+00	The plan is to train Malindi data clerks on Taifa Care usability for registration, queueing and appointment management, patient management best practices including quality data collection and account management.	Malindi - Lab Boardroom	Robin, Cliftone	Data Clerks (6).\r\nStudy Nurses (1).\r\nICT (2).	2025-12-09 17:33:17.115636+00	2025-12-09 17:33:17.115645+00	3	2
3	EV-20260126-808	Taifa Care Training Maternity	kwp2	2026-01-19 09:00:00+00	2026-01-23 03:30:00+00	The training focused on EMR navigation, patient admission workflows, clinical documentation, maternity-specific modules, and interdisciplinary use across departments. Practical demonstrations and user feedback sessions were incorporated to assess system usability and operational readiness	Malindi Lab Boardroom 	Kelvin Mbote 	Gynecologist: 1\r\nMedical Officers: 3\r\nNurses: 18\r\nMedical Officer Interns: 6\r\nClinical Officer Interns: 6\r\nICT Officers: 5\r\n\r\n	2026-01-26 09:34:59.969613+00	2026-01-26 10:15:23.441447+00	3	3
4	EV-20260127-8E8	Meeting, Malindi Taifa Care Status Update	kwp2	2026-01-27 14:00:00+00	2026-01-27 14:45:00+00	Discussion of current status in Malindi regarding server and networking.	Teams Online	Robin	Robin,\r\nCliftone,\r\nKelvin.	2026-01-27 12:09:28.050443+00	2026-01-27 12:09:28.050455+00	4	2
5	EV-20260128-3DE	ETL development: Form Capture and Data Mapping	kwp2	2026-01-13 16:00:00+00	2026-01-13 17:00:00+00	Presentation on milestones achieved regarding ETL development, particularly on data mapping and form creations.	Teams Online	Robin, Rajab	Kelvin,\r\nIsaac.	2026-01-28 10:40:33.452064+00	2026-01-28 10:40:33.452074+00	1	2
6	EV-20260128-D61	Review of ETL development milestones	kwp2	2026-01-19 17:00:00+00	2026-01-19 18:00:00+00	Review of the data extraction and transmission progress.	Teams Online	Robin	Moses K,\r\nKelvin,\r\nAngela,\r\nIsaac,\r\nRajab.	2026-01-28 10:57:19.417478+00	2026-01-28 10:57:19.417489+00	1	2
7	EV-20260128-0FC	Form capture review and data entry walkthrough	kwp2	2026-01-27 10:30:00+00	2026-01-27 13:35:00+00	Practical demo on ANC, Maternity workflow and patient management	Teams Online	Robin, Rajab	Kelvin,\r\nIsaac.	2026-01-28 11:08:57.226176+00	2026-01-28 11:08:57.226187+00	1	2
8	EV-20260128-E9D	Data Transmission (FHIR) Part One	kwp2	2026-01-28 12:00:00+00	2026-01-28 17:00:00+00	Presentation on progress with ETL development and transmission plan including resource needs, status update and proposed plan.	Teams Online	Robin, Rajab	Angela,\r\nKelvin,\r\nIsaac	2026-01-28 11:23:50.642279+00	2026-01-28 11:23:50.642288+00	1	2
11	EV-20260128-517	Data Transmission (FHIR) Part Two	kwp2	2026-01-29 10:00:00+00	2026-01-29 12:00:00+00	Practical demo to study team on the transmission process source to destination.	Teams Online	Robin, Rajab	Isaac,\r\nKelvin.	2026-01-28 13:21:39.931609+00	2026-01-28 13:21:39.931619+00	1	2
12	EV-20260511-5D4	Data Extraction and Transmission Completion	kwp2	2026-05-11 08:00:00+00	2026-05-15 17:00:00+00	Completion of form capture polishing, data extraction module and transmission testing and quality assurance.	Mariakani Office	Robin, Rajab, Kelvin	Rajab (Developer),\r\nRobin (Data Manager)\r\nKelvin (Nurse)	2026-05-11 16:35:26.880505+00	2026-05-11 16:37:51.212235+00	1	2
13	EV-20260511-43A	Data Form Capture Completion, ETL, Testing and Quality Assurance	kwp2	2026-05-11 08:00:00+00	2026-05-15 17:00:00+00	Completion of form capture polishing, data extraction module and transmission testing and quality assurance.	Mariakani Office	Robin, Rajab, Kelvin	Robin (Data Manager),\r\nRajab (Developer),\r\nKelvin (Nurse)	2026-05-11 16:42:05.812832+00	2026-05-11 16:42:05.812842+00	1	2
14	EV-20260511-F42	Release of Taifa Care  19.3.2 to Malindi site	kwp2	2026-04-18 16:00:00+00	2026-04-18 19:07:00+00	Release of Taifa Care version 19.3 bundled with study varibales.	Teams Online	Cliftone, Robin, Rajab	Cliftone,\r\nRobin	2026-05-11 16:54:33.334549+00	2026-05-11 16:54:33.334557+00	5	2
15	EV-20260511-1C2	Update of site EMR to current release, 19.3.3	kwp2	2026-03-23 19:00:00+00	2026-05-11 21:00:00+00	Updating the site, Malindi hospital with the current Taifa care package support report generation.	Malindi	Cliftone	Cliftone	2026-05-11 17:09:52.445389+00	2026-05-11 17:14:55.817684+00	5	2
16	EV-20260511-0D9	Update of site EMR to current release, 19.3.3- Part2	kwp2	2026-05-11 16:00:00+00	2026-05-11 19:00:00+00	Updating the site, Malindi hospital with the current Taifa care package constituting polish forms particularly Labor and Delivery.	Malindi	Cliftone, Robin, Rajab	Cliftone	2026-05-11 17:16:40.880516+00	2026-05-11 17:16:40.880526+00	5	2
\.


--
-- Data for Name: ems_outcome; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.ems_outcome (id, start_date, end_date, duration, rappo, topics, outcome_text, recommendation, created_at, updated_at, event_id) FROM stdin;
3	2025-11-13 09:00:00+00	2025-11-13 13:59:00+00	5	Robin	Introduction to EMR systems and evolution to Taifa Care.\nNavigation, modules, system features\nPatient registration and mandatory data elements.\nOpenMRS Id generation, assignment and use of other identifiers.\nQueue management and patient flow.\nHandling CCC and ANC clients.\nMother–child linkage.\nPractical: dummy patient registration, retrieval, data review and cleaning.	Participants familiarized with Taifa care and its significance in digital evolution of medical records data management.\n\nParticipants would demonstrate the process of managing patients at registration to other stations.\n\nAll participants successfully registered a patient, successfully demonstrated the retrieval process and check in processes.\n\nGaps:\nEntry of required but unavailable data as patient may not be in a position to provide the data.\nProcedure of verifying documents that are unavailable at the time of data collection.\n	Hospital to develop an SOP for registration workflow, roles, and responsibilities .	2025-12-09 17:34:48.634666+00	2025-12-09 17:34:48.634675+00	2
4	2025-11-14 09:00:00+00	2025-11-14 15:35:00+00	5	Robin	Recap of previous session.\nSHA and Taifa Care integration.\nPatient management workflows.\nData quality, security, and device management.\nAssessment test on system use and data handling.	Participants understood most of previous day’s concepts based on evaluation of the success of the recap session.\nSHA integration with Taifa Care simplifies particularly for registered SHA patients.\nScored assessment results: Avg 6/15, Median 4, Range 4–9\nGaps:\nMost trainees haven’t adequately aligned with current demands for good governance ensuring confidentiality and security of data.	ICT to develop SOP on device management\nProvide structured data-handling training aligned with regulations\nClarify roles and responsibilities through documented guidelines\nNeed for clarity on the scope of work and roles. 	2025-12-09 17:36:02.385673+00	2025-12-09 17:36:02.385685+00	2
11	2026-05-18 19:00:00+00	2026-04-18 21:00:00+00	2	Robin	1. EMR instance upgrade.\n2. Variable review on the live instance at the site.\n3. Feedback gathering.	Upgrade the site EMR to version 19.3, the updated version circulated country wide following overhaul changes resulting from the user feedback.\nBundled the updated version to include the additional variables and the data extraction module.\nSome variables were either missing or had logic failure resulting to hidden variables.\nReport extraction module wasn't working requiring review of the ETL	Review of missing variables and failing logics using the test EMR instance, consolidating feedback and sharing with the developer.\nDeveloper/ Stawisha HMIS to review the ETL for report extraction. HMIS can then share the feedback with the developer for updating/fixing the ETL.	2026-05-14 06:24:18.998511+00	2026-05-14 06:24:18.998522+00	14
5	2026-01-19 09:00:00+00	2026-01-23 14:00:00+00	25	Kelvin Mbote	The training focused on EMR navigation, patient admission workflows, clinical documentation, maternity-specific modules, and interdisciplinary use across departments. \nPractical demonstrations and user feedback sessions were incorporated to assess system usability and operational readiness.	Outcome\nOverall, participants reported that the EMR system is user-friendly and easy to navigate. Users expressed confidence in performing basic documentation tasks. However, concerns were raised regarding the length and complexity of the patient admission process, with recommendations to streamline workflows to improve efficiency during peak clinical hours.\n\nChallenges \n5.1 System Performance\n•\tSlow system response attributed to inadequate internet speed, leading to delays in real-time data entry.\n5.2 Clinical Handover\n•\tHandover between shifts using the EMR was reported as challenging.\n•\tUsers recommended development of a patient summary panel to provide a concise overview of key clinical information.\n5.3 Equipment Constraints\n•\tLimited availability of anthropometric devices, including:\no\tBlood pressure machines\no\tSPO2 monitors\n•\tAbsence of a weighing scale and height board in the maternity unit.\n5.4 Theatre Documentation\n•\tTheatre is not currently configured as a ward within the EMR.\n•\tUsers recommended enabling comprehensive theatre documentation and generation of a theatre list.\n5.5 Notifications and Alerts\n•\tLack of automated alerts for clinicians when results require review.\n•\tNo alert mechanism for abnormal clinical values.\n5.6 Partograph Design\n•\tCurrent partograph design requires multiple entries.\n•\tRecommendation to allow entry of multiple parameters (FHR, BP, pulse, membranes) in a single line per observation.\n5.7 Staffing and Infrastructure\n•\tThe new maternity unit is spatially divided into multiple rooms, unlike the current centralized setup.\n•\tThis raises concerns regarding staffing distribution and availability of tablets across:\no\tAntenatal Clinic (ANC)\no\tLabour Room\no\tPostnatal Care (PNC)\no\tPost-Caesarean Section areas\n\n Conclusion\nThe EMR training at Malindi Sub-County Hospital was successfully conducted and demonstrated strong user acceptance of the system. Addressing the identified challenges related to system performance, workflow efficiency, equipment availability, staffing, and missing forms will be critical to achieving optimal EMR utilization and supporting high-quality maternity care. These findings will inform ongoing EMR system refinement and implementation under the PROTECT Project.	6. User Recommendations\nParticipants proposed the following system improvements:\n•\tCapture birth weight in grams instead of kilograms.\n•\tEnhance prescription module to allow documentation of infusion rates in drops per minute, e.g. magnesium sulphate.\n•\tIntegrate all departments, including laboratory and pharmacy, into a unified EMR workflow.\n•\tInclude a field to indicate whether data entry is real-time or retrospective.\n•\tEnable automatic generation of sequential admission numbers per department.\n7. Missing EMR Forms\nThe following essential maternity forms were identified as missing:\n•\tMCH inpatient form with obstetric history\n•\tBlood transfusion form\n•\tAnaesthetist form\n•\tTheater Nurse Form \n•\tDrug administration chart\n•\tDischarge against medical advice form\n•\tReferral form\n•\tDischarge form with auto-population of relevant patient history\n•\tAutomated maternity reports generation	2026-01-26 09:47:45.011115+00	2026-01-26 10:14:06.50523+00	3
6	2026-01-27 14:00:00+00	2026-01-27 14:45:00+00	0.8	Robin	1.\tUpdate on the status of the current EMR regarding SHA integration, stutus on EMR version, user account creation and wards & beds mapping and tagging.\n2.\tInternet, server access, performance challenges and proposed solutions.\n3.\tInvoicing procedures for consultants.	1.\tHIE integration was done successfully after the latest update on 25/11/2025.\n2.\tLatest/new version of EMR, 19.3.0 cannot be rollout prior to training of users on the updated features, workflow etc. There’s a plan to conduct this training across the country in two weeks’ time. Team to consult Cliftone/Moses Keya for available slots to include members from the team.\n3.\tFrom version 19.3.0, all clinical users (last mile users offering services) are required to have valid license to attend to patient through the EMR. At registration, only ID number and category of licensing body are required, the rest of information preloads due to integration with the respective databases\n4.\tServer in Malindi requires an upgrade preferably replacement with higher performance desktop/workstation/HPE server/server following evaluation of quotations available and/or the quotations to be shared following specs from Cliftone/Rajab.\n5.\tMalindi network challenge requires a review meeting to discuss the most appropriate execution plan to address the current IP conflict issue. Proposed plan will be share with the team to review and provide further guidance. Proposed number of support need include at least 7 people (constituting 2 Malindi ICT members and others).	1.\tUpgrade to higher performance server that can effectively supported projected high number of users (about 40) as well as fasten report and other data extraction.\n2.\tTroubleshooting of Malindi network for DHCP IP routing resulting to IP conflict be conducted layer to layer to identify devices causing these challenges.	2026-01-27 12:57:03.427659+00	2026-01-27 12:57:03.427671+00	4
7	2026-01-13 16:00:00+00	2026-01-13 17:00:00+00	1	Robin	1. Data / variable Mapping and form creation.\n2. Review on timelines.	1. Project tracker and timeline shared constituting gantt chart of timeline breakdown 02/12/2025 to 21/01/2026.\n2. Variable mapping incomplete as it only contains mapping of concepts from the EMR, expected complete mapping documentation by Friday, 16/01/2026 that constitutes bothe source(EMR) and target(REDCap) databases.\n3. Development of both forms, tables and variable mapping on the EMR complete currently working on the ETL/pipeline development estimated completion time is Friday, 16/01/2026.\n4. Shared instance to facilitate testing and identification of any missing variables.	Detailed documentation for bothe data mapping and ETL development for review and Quality assurance.	2026-01-28 10:45:47.549825+00	2026-01-28 10:52:23.074698+00	5
8	2026-01-19 17:00:00+00	2026-01-19 18:00:00+00	1	Robin	1. Review on expected deliverables regarding; creation of test environment, Form and Data Capture Setup, pending documentations for data mapping, update on progress with ETL development as well as proposed transmission plan.\n2. Status of test instance missing:\n•\tMCH-Inpatient Form\n•\tMCH Partograph\n•\tICD-10 for diagnosis has not been activated (**currently using ICD-11)\n•\tDelivery form\n2. Demonstration of data pipeline and output.\n3. Recommendation on affordable servers/workstations/desktops recommended for Taifa Care server hosting.\n4. Communication and response time to queries.	Meeting scheduled to present practical demo on ANC outpatient and inpatient(maternity) workflows, data entry and patient management using the new version.	Clarity and transparency on challenges encountered hindering progress as well improved communication by the developer.	2026-01-28 11:04:56.542916+00	2026-01-28 11:04:56.542927+00	6
9	2026-01-27 10:30:00+00	2026-01-27 13:35:00+00	2	Robin	1. EMR forms and workflow from registration to delivery.\n2. Logical flow and implementation of initially missing variables.\n3. Review of missing forms, ANC and Maternity 	1. Mismatching variables for instance occupation in the EMR is fed in as a multiple choice response while in study database this field is a radio.\n2. Review of fields for missingness, misalignment, logical flow is evidently necessary to improve quality of data capture.\n3. Clerking patient before admission is necessary, Kelvin should share the admission form that would be used for reference while consulting for addition of this forms.\n4. date of  onset should be date and time.\n5. All calculated fields for number of durations, etc be reviewed.\n6. Team to explore mapping of vaccine and medication history whiled pulling data.	 Consider DHA's recommendation for generic approach to inpatient clerking.	2026-01-28 11:20:04.814537+00	2026-01-28 11:20:04.814548+00	7
10	2026-01-28 12:00:00+00	2026-01-28 13:15:00+00	1.3	Robin	1. Completion of data mapping and sharing.\n2. Update on transmission progress and pending activities.	1. Data mapping to be updated using the shared template as a guide to complete documentation.\n2. Separate/ portable module for transmission to be shared with Study data manager for cloning and persistence for future references. This would also include a markdown showing procedures implemented and workflow for installation and execution of the module.\n3. Test url and api token shared for testing of FHIR fire transmission source(EMR)-> Research Database (REDCap). Questions still pending on modality of transfer i.e update/append depending on Uganda central data management team's recommendation including staging table need.\n4. The simplex( one way communication) has been implemented from source to destination only. However, the source the source will identify if the record(s) exists using transmission output code (http codes for success, failed etc). An aku table has been created separately in the EMR that will interact with the module to extract/fetch data transmitted through FHIR. The tables after each successful transmission to avoid duplication.\n5. Review on vitals needed to decide on which of the likely multiple vitals' data should be selected for transmission. Developers can use defined logic to extract these data based on recommendation by Clinical lead following consultations.	Schedule  by 4PM a practical and technical driven meeting to test the transmission and troubleshoot errors likely to be encountered (Rajab & Robin).\nClean demo on demonstration to the rest of the team on Thursday, 29/01/2026 at 10 AM.	2026-01-28 11:43:17.525068+00	2026-01-28 11:43:17.525078+00	8
12	2026-05-11 17:00:00+00	2026-05-11 21:00:00+00	4	Robin	1. Review of feedback and recommendations from the existing version and additional variables.\n2. Fixing failing logics in the workflow (forms and frontend).\n3. Adding Missing variables.\n4. Updating the extraction module to include the updated ANC initial visit module.\n5. Upload of the package and sharing for the site for upgrade	1. Reinstated the most polished forms following last review by replacing existing ANC and Maternity forms previously replaced after variable mapping and addition of study specific variables.\n2. Reviewed, fixed the failing logical workflows to enhance workflow and restoring existing but hidden variables  previously reported as missing due to logic failure.\n3. With the help of the study nurse, added the identified missing variable relevant in a routine clinical setting.\n4. Rebuilt the instance and instance, reviewed the effected changes, exported the package and shared with the site HMIS for site upgrade.	The county is conducting a county wide cloud installation and migration of sites using on-premise server to cloud-based server hosting, Malindi included. The HMIS to collaborate with the palladium to oversee migration of the site cloud by 12th May 2026.\nPost-delivery variables initially mapped to MCH Postnatal, however, the study data collection ends at discharge. These variables should be migrated to Post- delivery form.	2026-05-14 06:52:55.817786+00	2026-05-14 06:52:55.817795+00	15
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 31, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 6, true);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 6, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 12, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 17, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: ems_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.ems_category_id_seq', 5, true);


--
-- Name: ems_event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.ems_event_id_seq', 16, true);


--
-- Name: ems_outcome_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.ems_outcome_id_seq', 12, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: ems_category ems_category_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ems_category
    ADD CONSTRAINT ems_category_name_key UNIQUE (name);


--
-- Name: ems_category ems_category_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ems_category
    ADD CONSTRAINT ems_category_pkey PRIMARY KEY (id);


--
-- Name: ems_event ems_event_event_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ems_event
    ADD CONSTRAINT ems_event_event_id_key UNIQUE (event_id);


--
-- Name: ems_event ems_event_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ems_event
    ADD CONSTRAINT ems_event_pkey PRIMARY KEY (id);


--
-- Name: ems_outcome ems_outcome_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ems_outcome
    ADD CONSTRAINT ems_outcome_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: ems_category_name_2efa9857_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX ems_category_name_2efa9857_like ON public.ems_category USING btree (name varchar_pattern_ops);


--
-- Name: ems_event_category_id_51c44c69; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX ems_event_category_id_51c44c69 ON public.ems_event USING btree (category_id);


--
-- Name: ems_event_event_id_08bed8e0_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX ems_event_event_id_08bed8e0_like ON public.ems_event USING btree (event_id varchar_pattern_ops);


--
-- Name: ems_event_user_id_7bc7ea3c; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX ems_event_user_id_7bc7ea3c ON public.ems_event USING btree (user_id);


--
-- Name: ems_outcome_event_id_32d601d1; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX ems_outcome_event_id_32d601d1 ON public.ems_outcome USING btree (event_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ems_event ems_event_category_id_51c44c69_fk_ems_category_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ems_event
    ADD CONSTRAINT ems_event_category_id_51c44c69_fk_ems_category_id FOREIGN KEY (category_id) REFERENCES public.ems_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ems_event ems_event_user_id_7bc7ea3c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ems_event
    ADD CONSTRAINT ems_event_user_id_7bc7ea3c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ems_outcome ems_outcome_event_id_32d601d1_fk_ems_event_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ems_outcome
    ADD CONSTRAINT ems_outcome_event_id_32d601d1_fk_ems_event_id FOREIGN KEY (event_id) REFERENCES public.ems_event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict EYPO0FHVL8Tapu7jyxczeRf5dNVsg9kLcMbD0io3PpwxzWvFlGNLi1fuNji0Xof

